apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: IMAGE_PLACEHOLDER # replaced by kubectl set image in workflows
          ports:
            - containerPort: 3000 # adjust to your app
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: $K8S_NAMESPACE
