apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: $K8S_NAMESPACE
