apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: $K8S_NAMESPACE
spec:
  type: LoadBalancer
  selector:
    app: $APP_NAME
  ports:
    - port: 80
      targetPort: 3000 # match your app port
